<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>818b5c30-bfb1-44e5-96d0-c1415b1d1409</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.S3Events" Version="4.0.0" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.103.4" />
    <PackageReference Include="Google.GenAI" Version="1.24.0" />
    <PackageReference Include="PdfPig" Version="0.1.16" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
